name: Build OpenWrt for Armvirt

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      image:
        description: 'OpenWrt Firmware Url'
        required: false
        default: 'https://github.com/mlacker/Actions-OpenWrt/releases/download/R_202203151616/openwrt-armvirt-64-default-rootfs.tar.gz'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Package Armvirt as OpenWrt
      uses: ophub/flippy-openwrt-actions@main
      env:
        OPENWRT_ARMVIRT: ${{ github.event.inputs.image }}
        PACKAGE_SOC: s905d
        KERNEL_VERSION_NAME: 5.4.184
        WHOAMI: mlacker

    - name: Upload OpenWrt Firmware to Release
      uses: ncipollo/release-action@v1
      with:
        tag: openwrt_armvirt_v8_${{ env.PACKAGED_OUTPUTDATE }}
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          This is OpenWrt firmware for Armvirt 64
          * Firmware information
          Default IP: 192.168.1.1
          Default username: root
          Default password: password